// Conditional rules engine — type definitions (RULES_ENGINE_PLAN §3-4).
//
// A rule is an if-then statement evaluated against a transaction. The condition
// is a recursive boolean tree of leaf comparators glued by all/any/not; the
// actions are an ordered patch list. Both are stored as JSON text in the
// `rules` table and parsed into these shapes by the engine at read time.

import type { Tx } from '@/lib/store';

export type TxKind = NonNullable<Tx['kind']>;

// --- Conditions -----------------------------------------------------------

/** A leaf comparator over one transaction field. */
export type Leaf =
  | { field: 'merchant'; op: 'is' | 'contains' | 'startsWith'; value: string; caseInsensitive?: boolean }
  | { field: 'amount'; op: 'gt' | 'gte' | 'lt' | 'lte' | 'eq'; value: number }
  | { field: 'amount'; op: 'between'; value: [number, number] }
  | { field: 'account_id'; op: 'is'; value: string }
  | { field: 'account_id'; op: 'in'; value: string[] }
  | { field: 'category_id'; op: 'is'; value: string }
  | { field: 'category_id'; op: 'in'; value: string[] }
  | { field: 'category_id'; op: 'is_null' }
  | { field: 'counterparty_id'; op: 'is'; value: string }
  | { field: 'counterparty_id'; op: 'is_null' }
  | { field: 'currency'; op: 'is'; value: string }
  | { field: 'date_dow'; op: 'in'; value: number[] }            // 0=Sun..6=Sat
  | { field: 'date_dom'; op: 'eq' | 'gte' | 'lte'; value: number } // day of month 1..31
  | { field: 'kind'; op: 'is'; value: TxKind }
  | { field: 'kind'; op: 'in'; value: TxKind[] }
  | { field: 'tag_id'; op: 'has'; value: string }
  | { field: 'tag_id'; op: 'has_any' | 'has_all'; value: string[] }
  | { field: 'note'; op: 'contains'; value: string; caseInsensitive?: boolean };

/** A condition is a leaf or a boolean combinator over sub-conditions. */
export type Condition =
  | { all: Condition[] }
  | { any: Condition[] }
  | { not: Condition }
  | Leaf;

// --- Actions --------------------------------------------------------------

/** One slice of a split action: a fraction (0..1) of the parent amount routed
 *  to a category. Fractions across a split action must sum to 1 (same rule the
 *  existing Split editor enforces). */
export interface SplitTemplate {
  fraction: number;
  categoryId: string | null;
  description?: string;
}

/** A single action applied to a matching transaction. Actions apply in order;
 *  later actions see earlier ones' results. */
export type Action =
  | { type: 'set_category'; categoryId: string | null }
  | { type: 'set_counterparty'; counterpartyId: string | null }
  | { type: 'set_merchant'; merchant: string }
  | { type: 'set_note'; note: string }
  | { type: 'set_kind'; kind: TxKind }
  | { type: 'add_tag'; tagId: string }
  | { type: 'remove_tag'; tagId: string }
  | { type: 'mark_reviewed' }
  | { type: 'split'; splits: SplitTemplate[] };

// --- Rule -----------------------------------------------------------------

/** A rule as projected into the store (condition + actions parsed from JSON). */
export interface Rule {
  id: string;
  ledgerId: string;
  name: string | null;
  /** Lower runs first; later (higher-priority-number) rules override earlier. */
  priority: number;
  condition: Condition;
  actions: Action[];
  isActive: boolean;
  /** Whether the rule re-fires on edit, not just on insert. Default false. */
  runOnEdit: boolean;
  lastAppliedAt: string | null;
}

/** Input for creating a rule (id + timestamps generated by the store/server). */
export interface NewRule {
  ledgerId: string;
  name?: string | null;
  priority?: number;
  condition: Condition;
  actions: Action[];
  isActive?: boolean;
  runOnEdit?: boolean;
}

/** The merged patch the engine produces for a transaction. Consumed by
 *  insertTxRow (on insert) or the backfill mutation (on existing rows). */
export interface RulePatch {
  categoryId?: string | null;
  counterpartyId?: string | null;
  merchant?: string;
  note?: string;
  kind?: TxKind;
  tagIdsAdd?: string[];
  tagIdsRemove?: string[];
  reviewed?: boolean;
  splits?: SplitTemplate[];
  /** Ids of every rule that contributed to this patch, in apply order. */
  appliedRuleIds: string[];
}
