import SwiftUI
import CoreGraphics

/// iOS export (2026-07-07 design) — the one-page monthly report PDF.
/// `MonthlyReportModel` carries PRE-FORMATTED strings (the caller formats money
/// via the store helpers) so the view and renderer stay pure and testable.
struct MonthlyReportModel {
    struct CategoryRow {
        let name: String
        let amount: String
        let pct: Int
    }
    struct MerchantRow {
        let name: String
        let amount: String
    }

    var ledgerName: String
    var monthLabel: String
    var income: String
    var spent: String
    var net: String
    var categories: [CategoryRow]
    var merchants: [MerchantRow]
    var generatedAt: String
}

/// Print-styled, fixed-width (US Letter, 612 pt) one-pager. Deliberately
/// hardcodes white/black so the PDF is theme-independent.
struct MonthlyReportView: View {
    let model: MonthlyReportModel

    private let palette: [Color] = [.blue, .green, .orange, .purple, .pink, .teal]

    var body: some View {
        VStack(alignment: .leading, spacing: 20) {
            // Header
            VStack(alignment: .leading, spacing: 2) {
                Text("finch").font(.caption).fontWeight(.semibold).foregroundStyle(.gray)
                Text("\(model.ledgerName) — \(model.monthLabel)")
                    .font(.title2).fontWeight(.bold)
            }

            // Stats row
            HStack(spacing: 24) {
                stat("Income", model.income)
                stat("Spent", model.spent)
                stat("Net", model.net)
                Spacer()
            }

            if !model.categories.isEmpty {
                section("Spending by category") {
                    ForEach(Array(model.categories.enumerated()), id: \.offset) { i, row in
                        HStack(spacing: 10) {
                            Circle().fill(palette[i % palette.count]).frame(width: 8, height: 8)
                            Text(row.name).font(.footnote)
                            Spacer()
                            Text("\(row.pct)%").font(.footnote.monospaced()).foregroundStyle(.gray)
                            Text(row.amount).font(.footnote).frame(minWidth: 80, alignment: .trailing)
                        }
                        .padding(.vertical, 3)
                        if i < model.categories.count - 1 { Divider() }
                    }
                }
            }

            if !model.merchants.isEmpty {
                section("Top merchants") {
                    ForEach(Array(model.merchants.enumerated()), id: \.offset) { i, row in
                        HStack {
                            Text(row.name).font(.footnote)
                            Spacer()
                            Text(row.amount).font(.footnote).frame(minWidth: 80, alignment: .trailing)
                        }
                        .padding(.vertical, 3)
                        if i < model.merchants.count - 1 { Divider() }
                    }
                }
            }

            Text("Generated by finch · \(model.generatedAt)")
                .font(.caption2).foregroundStyle(.gray)
        }
        .padding(36)
        .frame(width: 612, alignment: .leading)
        .background(Color.white)
        .foregroundStyle(.black)
        .environment(\.colorScheme, .light)
    }

    private func stat(_ label: String, _ value: String) -> some View {
        VStack(alignment: .leading, spacing: 2) {
            Text(label).font(.caption2).foregroundStyle(.gray)
            Text(value).font(.headline)
        }
    }

    private func section<Content: View>(_ title: String, @ViewBuilder content: () -> Content) -> some View {
        VStack(alignment: .leading, spacing: 6) {
            Text(title.uppercased()).font(.caption2).fontWeight(.semibold).foregroundStyle(.gray)
            content()
        }
    }
}

/// Renders any SwiftUI view into a single-page PDF (content-sized height).
@MainActor
enum ReportPdf {
    static func render<V: View>(_ view: V, width: CGFloat = 612) -> Data? {
        let renderer = ImageRenderer(content: view)
        renderer.proposedSize = ProposedViewSize(width: width, height: nil)
        let data = NSMutableData()
        renderer.render { size, renderIn in
            var box = CGRect(origin: .zero, size: size)
            guard let consumer = CGDataConsumer(data: data as CFMutableData),
                  let ctx = CGContext(consumer: consumer, mediaBox: &box, nil) else { return }
            ctx.beginPDFPage(nil)
            renderIn(ctx)
            ctx.endPDFPage()
            ctx.closePDF()
        }
        return data.length > 0 ? data as Data : nil
    }
}
